// THIS FILE IS AUTOMATICALLY GENERATED BY THE AWS AMPLIFY CLI.
// DO NOT EDIT MANUALLY.

// This is a placeholder file. When you run `amplify init` and `amplify push`,
// this file will be populated with your actual backend configuration.

const awsmobile = {
    "aws_project_region": "us-east-1", // Example: "us-east-1"
    "aws_cognito_identity_pool_id": "us-east-1:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xxxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxxxxxxxxx",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
};

export default awsmobile;
