
import { Consultancy, ConsultancyStatus, User, CompanyQuery } from './types';

export const NAV_LINKS: { name: string; href: string }[] = [
  { name: 'Home', href: '#' },
  { name: 'About Us', href: '#' },
  { name: 'Scammers List', href: '#' },
  { name: 'Trusted Firms', href: '#' },
  { name: 'I Need Help', href: '#' },
];

export const MOCK_USERS: User[] = [
    { id: 1, email: 'user@example.com', password: 'password123', role: 'user' },
    { id: 2, email: 'admin@visascamalerts.dev', password: 'admin123', role: 'admin'},
];

export const MOCK_COMPANY_QUERIES: CompanyQuery[] = [
    {
        id: 1,
        companyName: 'SecurePath Immigration',
        companyEmail: 'compliance@securepath.de',
        firmType: 'Employment Agency',
        query: 'One of the reports listed under our name has inaccurate information. We would like to provide clarifying documents. Please let us know the process.',
        date: '2023-11-14',
        status: 'pending'
    },
    {
        id: 2,
        companyName: 'Honest Consultants Inc.',
        companyEmail: 'apply@honestconsultants.com',
        firmType: 'Career Consultancy',
        query: 'We would like to apply for the "Trusted Firm" status. We have been operating for 10 years with a clean record and can provide all necessary registration documents and client testimonials.',
        date: '2023-11-13',
        status: 'pending'
    }
];

export const MOCK_CONSULTANCIES: Consultancy[] = [
  {
    id: 1,
    name: 'Global Dream Careers',
    status: ConsultancyStatus.Scammer,
    submissionStatus: 'approved',
    story: "They took a huge advance fee for a job in Canada that never existed. They stopped answering calls after receiving the money. The documents they provided were all fake.",
    submittedBy: 'John D.',
    submitterFullName: 'John Doe',
    submitterEmail: 'john.doe.priv@email.com',
    date: '2023-10-15',
    proofUrl: 'https://picsum.photos/seed/proof1/400/300',
    address: '123 Fake Street, Scamsville, ON, Canada',
    contactNumbers: ['+1-555-0101'],
    email: 'contact@globaldreamcareers.fake',
    website: 'https://globaldreamcareers.fake',
    socialMedia: { facebook: 'globaldreamcareers' }
  },
  {
    id: 2,
    name: 'SecurePath Immigration',
    status: ConsultancyStatus.Trusted,
    submissionStatus: 'approved',
    story: "Excellent service from start to finish. They were transparent about all costs and processes. I successfully got my work visa for Germany. Highly recommended.",
    submittedBy: 'Priya S.',
    submitterFullName: 'Priya Sharma',
    submitterEmail: 'priya.s.secure@email.com',
    date: '2023-09-22',
    address: '456 Trust Ave, Berlin, Germany',
    contactNumbers: ['+49 30 555-0102'],
    email: 'info@securepath.de',
    website: 'https://securepath.de',
    socialMedia: { linkedin: 'securepath-immigration' }
  },
  {
    id: 3,
    name: 'EasyVisa Now',
    status: ConsultancyStatus.Scammer,
    submissionStatus: 'approved',
    story: "Complete fraud. Promised a UK work visa in 3 months. After 6 months of excuses, their office was closed and their website was down. Lost over $5000.",
    submittedBy: 'Ahmed K.',
    submitterFullName: 'Ahmed Khan',
    submitterEmail: 'ahmed.k.main@email.com',
    date: '2023-11-01',
    address: '789 Deception Blvd, London, UK',
    contactNumbers: ['+44 20 5555 0103'],
    email: 'support@easyvisanow.scam',
    website: 'http://easyvisanow.scam',
  },
  {
    id: 4,
    name: 'FirstStep Overseas',
    status: ConsultancyStatus.Trusted,
    submissionStatus: 'approved',
    story: "A very professional and government-registered agency. They guided me through every step for my Australian PR visa. Everything was handled perfectly.",
    submittedBy: 'Maria G.',
    submitterFullName: 'Maria Garcia',
    submitterEmail: 'maria.garcia.aus@email.com',
    date: '2023-08-10',
    address: '101 Reliable Way, Sydney, Australia',
    contactNumbers: ['+61 2 5555 0104'],
    email: 'contact@firststepoverseas.com.au',
    website: 'https://firststepoverseas.com.au',
  },
  {
    id: 5,
    name: 'Swift Job Placement',
    status: ConsultancyStatus.Scammer,
    submissionStatus: 'approved',
    story: "They create fake offer letters. I cross-verified with the supposed employer in Dubai, and they had no idea about the job opening. Be careful of them.",
    submittedBy: 'Chen W.',
    submitterFullName: 'Chen Wei',
    submitterEmail: 'chen.w.dxb@email.com',
    date: '2023-10-28',
    address: 'Unit 404, Mirage Tower, Dubai, UAE',
    contactNumbers: ['+971 4 555 0105'],
    email: 'jobs@swiftjob.ae',
    website: 'https://swiftjobplacement.ae',
  },
   {
    id: 6,
    name: 'Integrity Visa Corp',
    status: ConsultancyStatus.Trusted,
    submissionStatus: 'approved',
    story: "The name says it all. They operate with full integrity. I got my US H1B visa processed through them without any hassle. They are genuine.",
    submittedBy: 'David L.',
    submitterFullName: 'David Lee',
    submitterEmail: 'david.lee.usa@email.com',
    date: '2023-07-05',
    address: '200 Integrity Plaza, New York, NY, USA',
    contactNumbers: ['+1 212 555 0106'],
    email: 'help@integrityvisa.com',
    website: 'https://integrityvisa.com',
    socialMedia: { linkedin: 'integrity-visa-corp' }
  },
  {
    id: 7,
    name: 'FlyHigh Consultants',
    status: ConsultancyStatus.Scammer,
    submissionStatus: 'approved',
    story: "They ask for money through unofficial channels and provide no receipts. The 'visa' they provided was a poorly edited image. Stay away!",
    submittedBy: 'Fatima A.',
    submitterFullName: 'Fatima Ahmed',
    submitterEmail: 'fatima.ahmed.scam@email.com',
    date: '2023-11-05',
    proofUrl: 'https://picsum.photos/seed/proof7/400/300',
    address: 'Office 13, Shadow Building, Mumbai, India',
    contactNumbers: ['+91 22 5555 0107'],
    email: 'enquiry@flyhigh.biz'
  },
  {
    id: 13,
    name: 'Canada Direct Visas',
    status: ConsultancyStatus.Scammer,
    submissionStatus: 'pending',
    story: "This is a pending submission. They promised a job and visa for a fee of $2000. After payment, they sent a fake job offer and stopped replying. Their website looks professional, but it's a front for a scam operation. I have attached the bank transfer screenshot and the fake offer letter.",
    submittedBy: 'PendingUser1',
    submitterFullName: 'Samantha Ray',
    submitterEmail: 's.ray.pending@email.com',
    date: '2023-11-15',
    proofUrl: 'https://picsum.photos/seed/proof13/400/300',
    address: '1000 Pending Lane, Virtual Office',
    contactNumbers: ['+1-555-0113'],
    email: 'info@canadadirectvisas.com'
  },
  {
    id: 14,
    name: 'Genuine Pathways',
    status: ConsultancyStatus.Trusted,
    submissionStatus: 'pending',
    story: "This is another pending submission. I want to vouch for Genuine Pathways. They were extremely professional and helped me get my student visa for Ireland. They are a government-approved agency, and their fees are very reasonable. I've attached a photo of my visa and their official receipt.",
    submittedBy: 'HappyStudent',
    submitterFullName: 'Liam Murphy',
    submitterEmail: 'liam.murphy.ireland@email.com',
    date: '2023-11-14',
    proofUrl: 'https://picsum.photos/seed/proof14/400/300',
    address: '25 Trustworthy Plaza, Dublin, Ireland',
    contactNumbers: ['+353 1 555 0114'],
    email: 'contact@genuinepathways.ie'
  },
];
