// This file is a placeholder for the mutations that will be
// auto-generated by the AWS Amplify CLI when you add an API (`amplify add api`).
// You can define your GraphQL schema in `amplify/backend/api/<YOUR_API_NAME>/schema.graphql`

export const createConsultancy = /* GraphQL */ `
  mutation CreateConsultancy(
    $input: CreateConsultancyInput!
    $condition: ModelConsultancyConditionInput
  ) {
    createConsultancy(input: $input, condition: $condition) {
      id
      name
      status
      submissionStatus
    }
  }
`;

export const updateConsultancy = /* GraphQL */ `
  mutation UpdateConsultancy(
    $input: UpdateConsultancyInput!
    $condition: ModelConsultancyConditionInput
  ) {
    updateConsultancy(input: $input, condition: $condition) {
      id
      submissionStatus
    }
  }
`;

export const createCompanyQuery = /* GraphQL */ `
  mutation CreateCompanyQuery(
    $input: CreateCompanyQueryInput!
    $condition: ModelCompanyQueryConditionInput
  ) {
    createCompanyQuery(input: $input, condition: $condition) {
      id
      companyName
      status
    }
  }
`;

export const updateCompanyQuery = /* GraphQL */ `
  mutation UpdateCompanyQuery(
    $input: UpdateCompanyQueryInput!
    $condition: ModelCompanyQueryConditionInput
  ) {
    updateCompanyQuery(input: $input, condition: $condition) {
      id
      status
    }
  }
`;
