// This file is a placeholder for the queries that will be
// auto-generated by the AWS Amplify CLI when you add an API (`amplify add api`).
// You can define your GraphQL schema in `amplify/backend/api/<YOUR_API_NAME>/schema.graphql`

export const getConsultancy = /* GraphQL */ `
  query GetConsultancy($id: ID!) {
    getConsultancy(id: $id) {
      id
      name
      status
      submissionStatus
      story
      submittedBy
      submitterFullName
      submitterEmail
      date
      proofUrl
      address
      contactNumbers
      email
      website
      # socialMedia is a JSON object, handle accordingly
    }
  }
`;

export const listConsultancys = /* GraphQL */ `
  query ListConsultancys(
    $filter: ModelConsultancyFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listConsultancys(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        name
        status
        submissionStatus
        date
        story
        submittedBy
      }
      nextToken
    }
  }
`;

export const listCompanyQuerys = /* GraphQL */ `
  query ListCompanyQuerys(
    $filter: ModelCompanyQueryFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listCompanyQuerys(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        companyName
        companyEmail
        date
        status
        query
      }
      nextToken
    }
  }
`;
